- name: Configure web server
  hosts: servera.lab.example.com

  tasks:
  - name: Install web server
    include_tasks: tasks/environment.yml
    vars:
      package: httpd
      service: httpd

  - name: Configure firewall
    include_tasks: tasks/firewall.yml
    vars:
      firewall_pkg: firewalld
      firewall_svc: firewalld
      rule:
      - http
      - https

  - name: Not sure
    import_tasks: tasks/placeholder.yml
    vars:
      file: /var/www/html/index.html

- name: Not sure either
  import_playbook: plays/test.yml
  vars:
    url: http://servera.lab.example.com

