---
- name: Playbook Control Lab
  hosts: webservers
  vars_files: vars.yml
  tasks:
    #Fail Fast Message
    - name: Example of a failed task
      ansible.builtin.fail:
        msg: This task can't run
      when: >
        ansible_facts['memtotal_mb'] < min_ram_mb or
        ansible_facts['distribution'] != "RedHat"

    #Install all Packages
    - name: Ensure required packages are present
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    #Enable and start services
    - name: Ensure required services are started
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

    #Block of config tasks
    - name: Start of block
      block:
      - name: Ensure directory exists
        ansible.builtin.file:
          path: "{{ ssl_cert_dir }}"
          state: directory
          mode: '0755' 

      - name: Copy all files
        ansible.builtin.copy:
          src: "{{ item['src'] }}"
          dest: "{{ item['dest'] }}"
        loop: "{{ web_config_files }}"
        notify: restart web service

      rescue:
      - name: Task failed
        ansible.builtin.debug:
          msg: One ore more of the configuration changes failed, but the web service is still active.

    #Configure the firewall
    - name: Configured firewalld
      ansible.builtin.firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      loop:
        - http
        - https

  #Add handlers
  handlers:
  - name: restart web service
    ansible.builtin.service:
      name: "{{ web_service }}"
      state: restarted

