---
- name: Do some stuff
  hosts: database_prod
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
  tasks:
    - name: Install the MariaDB package
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"
      when: ansible_facts['distribution'] == "RedHat"

    - name: Make sure the MariaDB service is running
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
