---
- name: Install and configure web service
  hosts:
    - servera.lab.example.com
    - serverb.lab.example.com
    - serverc.lab.example.com
    - serverd.lab.example.com

  tasks:
  - name: Import One
    import_tasks: tasks/web_tasks.yml

  - name: Import Two
    import_tasks: tasks/firewall_tasks.yml

  handlers:
  - name: restart httpd
    ansible.builtin.service:
      name: httpd
      state: restarted
